### ISSUE TITLE
Diseñar el API que permite generar los captchas (un endpoint para la solicitud, y un endpoint para la validación)

### ISSUE THREAD

**Issue by davidaam** [jfuenmayor96/ci4712-ui-designer#5]

**Comment by alfredojf** [comment]
Creo que esto esta listo. La documentacion esta en https://github.com/jfuenmayor96/ci4712-ui-designer/blob/4d5412e130ab86cfd74235b0ef03f85cbbc083ee/servecaptcha/docs/endpoints.md
